// CHAMBRES
export const GET_CHAMBRE = 'GET_CHAMBRE'
export const ADD_CHAMBRE = 'ADD_CHAMBRE'
export const DELETE_CHAMBRE = 'DELETE_CHAMBRE'
export const UPDATE_CHAMBRE = 'UPDATE_CHAMBRE'


// CATEGORIES
export const GET_CATEGORIE = 'GET_CATEGORIE'
export const ADD_CATEGORIE = 'ADD_CATEGORIE'
export const DELETE_CATEGORIE = 'DELETE_CATEGORIE'
export const UPDATE_CATEGORIE = 'UPDATE_CATEGORIE'
