import {
  ADD_CHAMBRE,
  DELETE_CHAMBRE,
  GET_CHAMBRE,
  UPDATE_CHAMBRE,
} from '../actions/types';

const initialState = {
  chambres: [
    {
      id: 1,
      nom: 'Suite exécutive',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id nulla corrupti',
      categorie_id: 1,
      categorie: 'LES SUITES',
      prix: '80 000',
      petit_dejeuner: true,
      images: [
        'assets/images/biens/suite_executive/1.jpg',
        'assets/images/biens/suite_executive/2.jpg',
        'assets/images/biens/suite_executive/3.jpg',
        'assets/images/biens/suite_executive/4.jpg',
        'assets/images/biens/suite_executive/5.jpg',
      ],
      vote: 3,
      periode: 'jour',
      interval: '1-6 janv',
      date: '05/02/2022',
      adresse: 'Abidjan',
      commentaires: [],
      nb_max_personne: 10,
      nb_chambre: 3,
      nb_salle_bain: 2,
      followers: [],
    },
    {
      id: 2,
      nom: 'Suite junior',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id nulla corrupti',
      categorie_id: 1,
      categorie: 'LES SUITES',
      prix: '60 000',
      petit_dejeuner: true,
      images: [
        'assets/images/biens/suite_executive/3.jpg',
        'assets/images/biens/suite_executive/4.jpg',
        'assets/images/biens/suite_executive/5.jpg',
        'assets/images/biens/suite_executive/6.jpg',
        'assets/images/biens/suite_executive/7.jpg',
      ],
      vote: 4,
      periode: 'jour',
      interval: '1-6 janv',
      date: '05/02/2022',
      adresse: 'Abidjan',
      commentaires: [],
      nb_max_personne: 10,
      nb_chambre: 3,
      nb_salle_bain: 2,
      followers: [],
    },
    {
      id: 3,
      nom: 'Supérieur deluxe',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id nulla corrupti',
      categorie_id: 2,
      categorie: 'LES SUPÉRIEURES',
      prix: '55 000',
      petit_dejeuner: true,
      images: [
        'assets/images/biens/suite_executive/1.jpg',
        'assets/images/biens/suite_executive/2.jpg',
        'assets/images/biens/suite_executive/3.jpg',
        'assets/images/biens/suite_executive/4.jpg',
        'assets/images/biens/suite_executive/5.jpg',
      ],
      vote: 3,
      periode: 'jour',
      interval: '22-30 Fev',
      date: '08/05/2022',
      adresse: 'Abidjan',
      commentaires: [],
      nb_max_personne: 5,
      nb_chambre: 7,
      nb_salle_bain: 2,
      followers: [],
    },
    {
      id: 4,
      nom: 'Supérieur 1',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id nulla corrupti',
      categorie_id: 2,
      categorie: 'LES SUPÉRIEURES',
      prix: '50 000',
      petit_dejeuner: true,
      images: [
        'assets/images/biens/suite_executive/2.jpg',
        'assets/images/biens/suite_executive/3.jpg',
        'assets/images/biens/suite_executive/4.jpg',
        'assets/images/biens/suite_executive/5.jpg',
        'assets/images/biens/suite_executive/6.jpg',
      ],
      vote: 4,
      periode: 'nuit',
      interval: '22-30 Fev',
      date: '08/05/2022',
      adresse: 'Abidjan',
      commentaires: [],
      nb_max_personne: 5,
      nb_chambre: 7,
      nb_salle_bain: 2,
      followers: [],
    },
    {
      id: 5,
      nom: 'Supérieur 2',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id nulla corrupti',
      categorie_id: 2,
      categorie: 'LES SUPÉRIEURES',
      prix: '50 000',
      petit_dejeuner: true,
      images: [
        'assets/images/biens/suite_executive/3.jpg',
        'assets/images/biens/suite_executive/4.jpg',
        'assets/images/biens/suite_executive/5.jpg',
        'assets/images/biens/suite_executive/6.jpg',
        'assets/images/biens/suite_executive/7.jpg',
      ],
      vote: 4,
      periode: 'jour',
      interval: '22-30 Fev',
      date: '02/09/2022',
      adresse: 'Abidjan',
      commentaires: [],
      nb_max_personne: 5,
      nb_chambre: 7,
      nb_salle_bain: 2,
      followers: [],
    },
    {
      id: 6,
      nom: 'Studio deluxe',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id nulla corrupti',
      categorie_id: 3,
      categorie: 'LES STUDIOS',
      prix: '45 000',
      petit_dejeuner: true,
      images: [
        'assets/images/biens/suite_executive/3.jpg',
        'assets/images/biens/suite_executive/4.jpg',
        'assets/images/biens/suite_executive/5.jpg',
        'assets/images/biens/suite_executive/6.jpg',
        'assets/images/biens/suite_executive/7.jpg',
      ],
      vote: 4,
      periode: 'jour',
      interval: '22-30 Fev',
      date: '04/09/2022',
      adresse: 'Abidjan',
      commentaires: [],
      nb_max_personne: 5,
      nb_chambre: 7,
      nb_salle_bain: 2,
      followers: [],
    },
    {
      id: 7,
      nom: 'Studio 1',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id nulla corrupti',
      categorie_id: 3,
      categorie: 'LES STUDIOS',
      prix: '40 000',
      petit_dejeuner: true,
      images: [
        'assets/images/biens/suite_executive/4.jpg',
        'assets/images/biens/suite_executive/5.jpg',
        'assets/images/biens/suite_executive/6.jpg',
        'assets/images/biens/suite_executive/7.jpg',
        'assets/images/biens/suite_executive/8.jpg',
      ],
      vote: 4,
      periode: 'jour',
      interval: '22-30 Fev',
      date: '04/09/2022',
      adresse: 'Abidjan',
      commentaires: [],
      nb_max_personne: 5,
      nb_chambre: 7,
      nb_salle_bain: 2,
      followers: [],
    },
    {
      id: 8,
      nom: 'Studio 2',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id nulla corrupti',
      categorie_id: 3,
      categorie: 'LES STUDIOS',
      prix: '40 000',
      petit_dejeuner: true,
      images: [
        'assets/images/biens/suite_executive/8.jpg',
        'assets/images/biens/suite_executive/9.jpg',
        'assets/images/biens/suite_executive/10.jpg',
        'assets/images/biens/suite_executive/1.jpg',
        'assets/images/biens/suite_executive/2.jpg',
      ],
      vote: 4,
      periode: 'nuit',
      interval: '22-30 Fev',
      date: '04/09/2022',
      adresse: 'Abidjan',
      commentaires: [],
      nb_max_personne: 5,
      nb_chambre: 7,
      nb_salle_bain: 2,
      followers: [],
    },
    {
      id: 9,
      nom: 'Standard deluxe',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id nulla corrupti',
      categorie_id: 4,
      categorie: 'LES STANDARDS',
      prix: '35 000',
      petit_dejeuner: true,
      images: [
        'assets/images/biens/suite_executive/1.jpg',
        'assets/images/biens/suite_executive/2.jpg',
        'assets/images/biens/suite_executive/3.jpg',
        'assets/images/biens/suite_executive/4.jpg',
        'assets/images/biens/suite_executive/5.jpg',
      ],
      vote: 4,
      periode: 'jour',
      interval: '22-30 Fev',
      date: '04/09/2022',
      adresse: 'Abidjan',
      commentaires: [],
      nb_max_personne: 5,
      nb_chambre: 7,
      nb_salle_bain: 2,
      followers: [],
    },
    {
      id: 10,
      nom: 'Standard 1',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id nulla corrupti',
      categorie_id: 4,
      categorie: 'LES STANDARDS',
      prix: '30 000',
      petit_dejeuner: true,
      images: [
        'assets/images/biens/suite_executive/3.jpg',
        'assets/images/biens/suite_executive/4.jpg',
        'assets/images/biens/suite_executive/5.jpg',
        'assets/images/biens/suite_executive/6.jpg',
        'assets/images/biens/suite_executive/7.jpg',
      ],
      vote: 4,
      periode: 'jour',
      interval: '22-30 Fev',
      date: '04/09/2022',
      adresse: 'Abidjan',
      commentaires: [],
      nb_max_personne: 5,
      nb_chambre: 7,
      nb_salle_bain: 2,
      followers: [],
    },
    {
      id: 11,
      nom: 'Standard 2',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id nulla corrupti',
      categorie_id: 4,
      categorie: 'LES STANDARDS',
      prix: '30 000',
      petit_dejeuner: true,
      images: [
        'assets/images/biens/suite_executive/5.jpg',
        'assets/images/biens/suite_executive/6.jpg',
        'assets/images/biens/suite_executive/7.jpg',
        'assets/images/biens/suite_executive/8.jpg',
        'assets/images/biens/suite_executive/10.jpg',
      ],
      vote: 4,
      periode: 'jour',
      interval: '22-30 Fev',
      date: '04/09/2022',
      adresse: 'Abidjan',
      commentaires: [],
      nb_max_personne: 5,
      nb_chambre: 7,
      nb_salle_bain: 2,
      followers: [],
    },
  ],
};

export default function chambres(state = initialState, action) {
  const { type, payload } = action;
  switch (type) {
    case GET_CHAMBRE:
      return {
        ...state,
        chambres: payload,
      };

    case ADD_CHAMBRE:
      return {
        ...state,
        chambres: [...state.chambres, payload],
      };
    case UPDATE_CHAMBRE:
      return {
        ...state,
        chambres: state.chambres.map((chambre) =>
          chambre.id === payload.id ? payload : chambre
        ),
      };
    case DELETE_CHAMBRE:
      return {
        ...state,
        chambres: [
          ...state.chambres.filter((chambre) => chambre.id !== payload),
        ],
      };

    default:
      return state;
  }
}
